### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [breannansmith/scisim#4]
I follow the quickstart guide, and when `make` get the following errors:

`scisim-master/rigidbody2dqt4/GLWidget.cpp:19:53: fatal error: RigidBody2DUtils/RigidBody2DSceneParser.h: No such file or directory
compilation terminated.
`

My system is Ubuntu16.04

**Comment by breannansmith** [comment]
Thanks for the report, the directory names were capitalized incorrectly which prevent compilation on Linux. I've pushed a patch, please reopen this issue if the problem persists!
