### ISSUE TITLE
What is python used for?

### ISSUE THREAD

**Issue by alecjacobson** [breannansmith/scisim#6]
I'd eventually like to use scisim as a library from C++ code. I'm having trouble getting the rigidbody3dqt4 example from the README working because of issues combining python and clang (probably due to some python version mess homebrew created). Is python just used for the qt gui?

Is there a minimal gui-less/python-less version of the rigidbody3d example?

**Comment by alecjacobson** [comment]
My question might be moot now. I managed to get the minimal demo built by forcing CMAKE to find my homebrew-installed python:

    cmake -DUSE_QT4=ON -DUSE_HDF5=ON -DUSE_PYTHON=ON -DPYTHON_LIBRARY=/usr/local/Cellar/python//2.7.13/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python//2.7.13/Frameworks/Python.framework/Headers ..

**Comment by breannansmith** [comment]
Python is only required if you want to write callbacks to customize the behavior of SCISim. I've used this primarily for scripting kinematic bodies, but callbacks are also exposed for changing parameters of the contact model and so forth. I will clarify the use-cases of Python in the readme.
